name: workflow

on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print a Message
        run: |
          echo "Hello, GitHub Actions!"
          sleep 10
